#!/usr/bin/env ksh

PATH=/bin:/usr/bin

#curl -s http://www.ip-adress.eu | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}'

case x${1} in
	x4)
		curl -s https://www.moanmyip.com \
		    | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' \
		    | uniq
	;;
	x6)
		curl -s https://www.moanmyip.com \
		    | egrep -o '(::)?[0-9a-fA-F]{1,4}(::?[0-9a-fA-F]{1,4}){1,7}(::)?' \
		    | uniq
	;;
	*)
		curl -s https://www.moanmyip.com \
		    | egrep -o '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|(::)?[0-9a-fA-F]{1,4}(::?[0-9a-fA-F]{1,4}){1,7}(::)?' \
		    | uniq
	;;
esac
