#!/bin/bash
#
# netdrv - List the network drivers and interface associations on a device.
#
# Courtesy of [John Reinhart](https://unix.stackexchange.com/users/8928/jonathon-reinhart)
# on [StackExchange](https://unix.stackexchange.com/questions/41817/linux-how-to-find-the-device-driver-used-for-a-device)

PATH=/bin:/usr/bin

if [[ ! $(uname -o) =~ "Linux" ]]; then
    echo "ERROR: Must run on a GNU/Linux system."
    exit 2
fi

for f in /sys/class/net/*; do
    dev=$(basename $f)
    driver=$(readlink $f/device/driver/module)

    if [ $driver ]; then
        driver=$(basename $driver)
    fi

    addr=$(cat $f/address)
    operstate=$(cat $f/operstate)
    printf "%10s [%s]: %10s (%s)\n" "$dev" "$addr" "$driver" "$operstate"
done
