#!/usr/bin/env ksh
#
# Connect to serial port without remembering all the specifics.

PATH=/usr/bin

typeset LOG=""
typeset PORT="/dev/tty.usbserial-0001"
typeset -i BRATE=115200

if [[ $(uname -o) != "Darwin" ]]; then
	print -u2 "ERROR: This programs only runs on macos."
	exit 2
fi

case x${1} in
	"-l")
		LOG="-L"
	;;
	*) # "-h"|"--help") # TODO: Add proper CLI argument handling.
		print "usage: serial <-l>"
		print "       Shortcut for screen command."
		print "  -l   Enable output logging."
		exit 0
	;;
esac

if [[ -c ${PORT} ]]; then
	screen -A ${LOG} ${PORT} ${BRATE}
else
	print -u2 "ERROR: Unable to communicate with USB serial port."
	exit 1
fi

